// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: github.com/amazingchow/photon-dance-grpc-examples/grpc-file-transfer-tool/pb/messages.proto

package api

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type UploadStatusCode int32

const (
	UploadStatusCode_STATUS_CODE_UNKNOWN UploadStatusCode = 0
	UploadStatusCode_STATUS_CODE_OK      UploadStatusCode = 1
	UploadStatusCode_STATUS_CODE_FAILED  UploadStatusCode = 2
)

// Enum value maps for UploadStatusCode.
var (
	UploadStatusCode_name = map[int32]string{
		0: "STATUS_CODE_UNKNOWN",
		1: "STATUS_CODE_OK",
		2: "STATUS_CODE_FAILED",
	}
	UploadStatusCode_value = map[string]int32{
		"STATUS_CODE_UNKNOWN": 0,
		"STATUS_CODE_OK":      1,
		"STATUS_CODE_FAILED":  2,
	}
)

func (x UploadStatusCode) Enum() *UploadStatusCode {
	p := new(UploadStatusCode)
	*p = x
	return p
}

func (x UploadStatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UploadStatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_amazingchow_photon_dance_grpc_examples_grpc_file_transfer_tool_pb_messages_proto_enumTypes[0].Descriptor()
}

func (UploadStatusCode) Type() protoreflect.EnumType {
	return &file_github_com_amazingchow_photon_dance_grpc_examples_grpc_file_transfer_tool_pb_messages_proto_enumTypes[0]
}

func (x UploadStatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UploadStatusCode.Descriptor instead.
func (UploadStatusCode) EnumDescriptor() ([]byte, []int) {
	return file_github_com_amazingchow_photon_dance_grpc_examples_grpc_file_transfer_tool_pb_messages_proto_rawDescGZIP(), []int{0}
}

type FileChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content []byte `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_amazingchow_photon_dance_grpc_examples_grpc_file_transfer_tool_pb_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_amazingchow_photon_dance_grpc_examples_grpc_file_transfer_tool_pb_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_github_com_amazingchow_photon_dance_grpc_examples_grpc_file_transfer_tool_pb_messages_proto_rawDescGZIP(), []int{0}
}

func (x *FileChunk) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type UploadStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string           `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	Code    UploadStatusCode `protobuf:"varint,2,opt,name=Code,proto3,enum=amazingchow.photon_dance_grpc_examples.grpc_file_transfer_tool.UploadStatusCode" json:"Code,omitempty"`
}

func (x *UploadStatus) Reset() {
	*x = UploadStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_amazingchow_photon_dance_grpc_examples_grpc_file_transfer_tool_pb_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadStatus) ProtoMessage() {}

func (x *UploadStatus) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_amazingchow_photon_dance_grpc_examples_grpc_file_transfer_tool_pb_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadStatus.ProtoReflect.Descriptor instead.
func (*UploadStatus) Descriptor() ([]byte, []int) {
	return file_github_com_amazingchow_photon_dance_grpc_examples_grpc_file_transfer_tool_pb_messages_proto_rawDescGZIP(), []int{1}
}

func (x *UploadStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadStatus) GetCode() UploadStatusCode {
	if x != nil {
		return x.Code
	}
	return UploadStatusCode_STATUS_CODE_UNKNOWN
}

var File_github_com_amazingchow_photon_dance_grpc_examples_grpc_file_transfer_tool_pb_messages_proto protoreflect.FileDescriptor

var file_github_com_amazingchow_photon_dance_grpc_examples_grpc_file_transfer_tool_pb_messages_proto_rawDesc = []byte{
	0x0a, 0x5b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6d, 0x61,
	0x7a, 0x69, 0x6e, 0x67, 0x63, 0x68, 0x6f, 0x77, 0x2f, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x6e, 0x2d,
	0x64, 0x61, 0x6e, 0x63, 0x65, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x65, 0x78, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x66, 0x69, 0x6c, 0x65, 0x2d, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x2d, 0x74, 0x6f, 0x6f, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x3e, 0x61,
	0x6d, 0x61, 0x7a, 0x69, 0x6e, 0x67, 0x63, 0x68, 0x6f, 0x77, 0x2e, 0x70, 0x68, 0x6f, 0x74, 0x6f,
	0x6e, 0x5f, 0x64, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x65, 0x78, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x5f, 0x74, 0x6f, 0x6f, 0x6c, 0x22, 0x25, 0x0a,
	0x09, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x22, 0x8e, 0x01, 0x0a, 0x0c, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x64, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x50, 0x2e,
	0x61, 0x6d, 0x61, 0x7a, 0x69, 0x6e, 0x67, 0x63, 0x68, 0x6f, 0x77, 0x2e, 0x70, 0x68, 0x6f, 0x74,
	0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x65, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x66, 0x69, 0x6c, 0x65,
	0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x5f, 0x74, 0x6f, 0x6f, 0x6c, 0x2e, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x04, 0x43, 0x6f, 0x64, 0x65, 0x2a, 0x57, 0x0a, 0x10, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x17, 0x0a, 0x13, 0x53, 0x54, 0x41,
	0x54, 0x55, 0x53, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e,
	0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x43, 0x4f, 0x44,
	0x45, 0x5f, 0x4f, 0x4b, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53,
	0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x02, 0x32, 0xbb,
	0x01, 0x0a, 0x11, 0x47, 0x72, 0x70, 0x63, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0xa5, 0x01, 0x0a, 0x06, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12,
	0x49, 0x2e, 0x61, 0x6d, 0x61, 0x7a, 0x69, 0x6e, 0x67, 0x63, 0x68, 0x6f, 0x77, 0x2e, 0x70, 0x68,
	0x6f, 0x74, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x5f,
	0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x66, 0x69,
	0x6c, 0x65, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x5f, 0x74, 0x6f, 0x6f, 0x6c,
	0x2e, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x1a, 0x4c, 0x2e, 0x61, 0x6d, 0x61,
	0x7a, 0x69, 0x6e, 0x67, 0x63, 0x68, 0x6f, 0x77, 0x2e, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x6e, 0x5f,
	0x64, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x65, 0x78, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x73, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x5f, 0x74, 0x6f, 0x6f, 0x6c, 0x2e, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x28, 0x01, 0x42, 0x4f, 0x5a, 0x4d,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6d, 0x61, 0x7a, 0x69,
	0x6e, 0x67, 0x63, 0x68, 0x6f, 0x77, 0x2f, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x6e, 0x2d, 0x64, 0x61,
	0x6e, 0x63, 0x65, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x66, 0x69, 0x6c, 0x65, 0x2d, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x66, 0x65, 0x72, 0x2d, 0x74, 0x6f, 0x6f, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_amazingchow_photon_dance_grpc_examples_grpc_file_transfer_tool_pb_messages_proto_rawDescOnce sync.Once
	file_github_com_amazingchow_photon_dance_grpc_examples_grpc_file_transfer_tool_pb_messages_proto_rawDescData = file_github_com_amazingchow_photon_dance_grpc_examples_grpc_file_transfer_tool_pb_messages_proto_rawDesc
)

func file_github_com_amazingchow_photon_dance_grpc_examples_grpc_file_transfer_tool_pb_messages_proto_rawDescGZIP() []byte {
	file_github_com_amazingchow_photon_dance_grpc_examples_grpc_file_transfer_tool_pb_messages_proto_rawDescOnce.Do(func() {
		file_github_com_amazingchow_photon_dance_grpc_examples_grpc_file_transfer_tool_pb_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_amazingchow_photon_dance_grpc_examples_grpc_file_transfer_tool_pb_messages_proto_rawDescData)
	})
	return file_github_com_amazingchow_photon_dance_grpc_examples_grpc_file_transfer_tool_pb_messages_proto_rawDescData
}

var file_github_com_amazingchow_photon_dance_grpc_examples_grpc_file_transfer_tool_pb_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_github_com_amazingchow_photon_dance_grpc_examples_grpc_file_transfer_tool_pb_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_amazingchow_photon_dance_grpc_examples_grpc_file_transfer_tool_pb_messages_proto_goTypes = []interface{}{
	(UploadStatusCode)(0), // 0: amazingchow.photon_dance_grpc_examples.grpc_file_transfer_tool.UploadStatusCode
	(*FileChunk)(nil),     // 1: amazingchow.photon_dance_grpc_examples.grpc_file_transfer_tool.FileChunk
	(*UploadStatus)(nil),  // 2: amazingchow.photon_dance_grpc_examples.grpc_file_transfer_tool.UploadStatus
}
var file_github_com_amazingchow_photon_dance_grpc_examples_grpc_file_transfer_tool_pb_messages_proto_depIdxs = []int32{
	0, // 0: amazingchow.photon_dance_grpc_examples.grpc_file_transfer_tool.UploadStatus.Code:type_name -> amazingchow.photon_dance_grpc_examples.grpc_file_transfer_tool.UploadStatusCode
	1, // 1: amazingchow.photon_dance_grpc_examples.grpc_file_transfer_tool.GrpcStreamService.Upload:input_type -> amazingchow.photon_dance_grpc_examples.grpc_file_transfer_tool.FileChunk
	2, // 2: amazingchow.photon_dance_grpc_examples.grpc_file_transfer_tool.GrpcStreamService.Upload:output_type -> amazingchow.photon_dance_grpc_examples.grpc_file_transfer_tool.UploadStatus
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() {
	file_github_com_amazingchow_photon_dance_grpc_examples_grpc_file_transfer_tool_pb_messages_proto_init()
}
func file_github_com_amazingchow_photon_dance_grpc_examples_grpc_file_transfer_tool_pb_messages_proto_init() {
	if File_github_com_amazingchow_photon_dance_grpc_examples_grpc_file_transfer_tool_pb_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_amazingchow_photon_dance_grpc_examples_grpc_file_transfer_tool_pb_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_amazingchow_photon_dance_grpc_examples_grpc_file_transfer_tool_pb_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_amazingchow_photon_dance_grpc_examples_grpc_file_transfer_tool_pb_messages_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_amazingchow_photon_dance_grpc_examples_grpc_file_transfer_tool_pb_messages_proto_goTypes,
		DependencyIndexes: file_github_com_amazingchow_photon_dance_grpc_examples_grpc_file_transfer_tool_pb_messages_proto_depIdxs,
		EnumInfos:         file_github_com_amazingchow_photon_dance_grpc_examples_grpc_file_transfer_tool_pb_messages_proto_enumTypes,
		MessageInfos:      file_github_com_amazingchow_photon_dance_grpc_examples_grpc_file_transfer_tool_pb_messages_proto_msgTypes,
	}.Build()
	File_github_com_amazingchow_photon_dance_grpc_examples_grpc_file_transfer_tool_pb_messages_proto = out.File
	file_github_com_amazingchow_photon_dance_grpc_examples_grpc_file_transfer_tool_pb_messages_proto_rawDesc = nil
	file_github_com_amazingchow_photon_dance_grpc_examples_grpc_file_transfer_tool_pb_messages_proto_goTypes = nil
	file_github_com_amazingchow_photon_dance_grpc_examples_grpc_file_transfer_tool_pb_messages_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GrpcStreamServiceClient is the client API for GrpcStreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GrpcStreamServiceClient interface {
	Upload(ctx context.Context, opts ...grpc.CallOption) (GrpcStreamService_UploadClient, error)
}

type grpcStreamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGrpcStreamServiceClient(cc grpc.ClientConnInterface) GrpcStreamServiceClient {
	return &grpcStreamServiceClient{cc}
}

func (c *grpcStreamServiceClient) Upload(ctx context.Context, opts ...grpc.CallOption) (GrpcStreamService_UploadClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GrpcStreamService_serviceDesc.Streams[0], "/amazingchow.photon_dance_grpc_examples.grpc_file_transfer_tool.GrpcStreamService/Upload", opts...)
	if err != nil {
		return nil, err
	}
	x := &grpcStreamServiceUploadClient{stream}
	return x, nil
}

type GrpcStreamService_UploadClient interface {
	Send(*FileChunk) error
	CloseAndRecv() (*UploadStatus, error)
	grpc.ClientStream
}

type grpcStreamServiceUploadClient struct {
	grpc.ClientStream
}

func (x *grpcStreamServiceUploadClient) Send(m *FileChunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *grpcStreamServiceUploadClient) CloseAndRecv() (*UploadStatus, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UploadStatus)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GrpcStreamServiceServer is the server API for GrpcStreamService service.
type GrpcStreamServiceServer interface {
	Upload(GrpcStreamService_UploadServer) error
}

// UnimplementedGrpcStreamServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGrpcStreamServiceServer struct {
}

func (*UnimplementedGrpcStreamServiceServer) Upload(GrpcStreamService_UploadServer) error {
	return status.Errorf(codes.Unimplemented, "method Upload not implemented")
}

func RegisterGrpcStreamServiceServer(s *grpc.Server, srv GrpcStreamServiceServer) {
	s.RegisterService(&_GrpcStreamService_serviceDesc, srv)
}

func _GrpcStreamService_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GrpcStreamServiceServer).Upload(&grpcStreamServiceUploadServer{stream})
}

type GrpcStreamService_UploadServer interface {
	SendAndClose(*UploadStatus) error
	Recv() (*FileChunk, error)
	grpc.ServerStream
}

type grpcStreamServiceUploadServer struct {
	grpc.ServerStream
}

func (x *grpcStreamServiceUploadServer) SendAndClose(m *UploadStatus) error {
	return x.ServerStream.SendMsg(m)
}

func (x *grpcStreamServiceUploadServer) Recv() (*FileChunk, error) {
	m := new(FileChunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _GrpcStreamService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "amazingchow.photon_dance_grpc_examples.grpc_file_transfer_tool.GrpcStreamService",
	HandlerType: (*GrpcStreamServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upload",
			Handler:       _GrpcStreamService_Upload_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "github.com/amazingchow/photon-dance-grpc-examples/grpc-file-transfer-tool/pb/messages.proto",
}
